/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellResourcesRouteImport } from './routes/_shell.resources'
import { Route as ShellSchedulerRouteImport } from './routes/_shell.scheduler'
import { Route as ShellTasksRouteImport } from './routes/_shell.tasks'
import { Route as ShellWorkersRouteImport } from './routes/_shell.workers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResourcesRoute = ShellResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSchedulerRoute = ShellSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkersRoute = ShellWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/resources': typeof ShellResourcesRoute
  '/scheduler': typeof ShellSchedulerRoute
  '/tasks': typeof ShellTasksRoute
  '/workers': typeof ShellWorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/resources': typeof ShellResourcesRoute
  '/scheduler': typeof ShellSchedulerRoute
  '/tasks': typeof ShellTasksRoute
  '/workers': typeof ShellWorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/resources': typeof ShellResourcesRoute
  '/_shell/scheduler': typeof ShellSchedulerRoute
  '/_shell/tasks': typeof ShellTasksRoute
  '/_shell/workers': typeof ShellWorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/resources' | '/scheduler' | '/tasks' | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/resources' | '/scheduler' | '/tasks' | '/workers'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/dashboard'
    | '/_shell/resources'
    | '/_shell/scheduler'
    | '/_shell/tasks'
    | '/_shell/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/resources': {
      id: '/_shell/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ShellResourcesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scheduler': {
      id: '/_shell/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof ShellSchedulerRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workers': {
      id: '/_shell/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof ShellWorkersRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellResourcesRoute: typeof ShellResourcesRoute
  ShellSchedulerRoute: typeof ShellSchedulerRoute
  ShellTasksRoute: typeof ShellTasksRoute
  ShellWorkersRoute: typeof ShellWorkersRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellResourcesRoute: ShellResourcesRoute,
  ShellSchedulerRoute: ShellSchedulerRoute,
  ShellTasksRoute: ShellTasksRoute,
  ShellWorkersRoute: ShellWorkersRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
